require('general.pre-options')

require('plugins')
require('plugins.filetype')
require('plugins.nvim-lspconfig')
require('plugins.nvim-treesitter')
require('plugins.gitsigns')
require('plugins.nvim-tree')
require('plugins.telescope')
require('plugins.nvim-lualine')
require('plugins.nvim-autopairs')
require('plugins.nvim-ts-autotag')

require('general.options')
require('general.mappings')
